config/routes.rb
ChoreTracker::Application.routes.draw do
  # Generated routes for models
  resources :chores
  resources :tasks
  resources :children
  
  # Setting default route
  root to: 'chores#index'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
require 'simplecov'
SimpleCov.start 'rails'

class Child < ApplicationRecord
  has_many :chores
  has_many :tasks, through: :chores

  validates_presence_of :first_name
  validates_presence_of :last_name

  scope :alphabetical, -> { order('last_name, first_name') }
  scope :active, -> { where(active: true) }

  def name
    return first_name + " " + last_name
  end

  def points_earned
    self.chores.done.inject(0){|sum,chore| sum += chore.task.points}
  end 
      
end

app/models/chore.rb
class Chore < ApplicationRecord
  belongs_to :child
  belongs_to :task

  validates_date :due_on

  scope :by_task, -> { joins(:task).order('name') }
  scope :chronological, -> { order('due_on') }
  scope :pending, -> { where(completed: false) }
  scope :done, -> { where(completed: true) }
  scope :upcoming, -> { where('due_on >= ?', Date.today) }
  scope :past, -> { where('due_on < ?',  Date.today) }

  def status
    if completed then 'Completed' else 'Pending' end
  end

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :chores
  has_many :children, through: :chores

  validates_presence_of :name
  validates_numericality_of :points, only_integer: true, greater_than_or_equal_to: 0

  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index
    @children = Child.alphabetical.all
  end

  # GET /children/1
  # GET /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: "#{@child.name} was successfully created." }
        format.json { render action: 'show', status: :created, location: @child }
      else
        format.html { render action: 'new' }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: "#{@child.name}'s record was updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:first_name, :last_name, :active)
    end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.chronological.by_task.all
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chore }
      else
        format.html { render action: 'new' }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:child_id, :task_id, :due_on, :completed)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "#{@task.name} was successfully created." }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "#{@task.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :points, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<h2>Children in the system</h2>

<table>
  <tr>
    <th width="200" align="left">Name</th>
    <th width="120">Active</th>
    <th width="120">Earned Pts</th>
    <th></th>
  </tr>

<% @children.each do |child| %>
  <tr>
    <td><%= link_to child.name, child_path(child) %></td>
    <td align="center"><%= child.active ? "Yes" : "No" %></td>
    <td align="center"><%= child.points_earned %></td>
    <td><%= link_to 'Edit', edit_child_path(child) %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb

<p>
  <strong>First name:</strong>
  <%= @child.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @child.last_name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @child.active %>
</p>

<p>
  <strong>Points earned:</strong>
  <%= @child.points_earned %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.collection_select :child_id, Child.alphabetical.active.all, :id, :name, :prompt => "Select child..." %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.collection_select :task_id, Task.alphabetical.active.all, :id, :name, :prompt => "Select task..." %>
  </div>
  <div class="field">
    <%= f.label :due_on %><br />
    <%= f.date_select :due_on, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h2>Listing chores</h2>

<table>
  <tr>
    <th width="125" align="left">Child</th>
    <th width="200" align="left">Task</th>
    <th width="75">Due on</th>
    <th width="125">Completed</th>
    <th></th>
  </tr>

<% @chores.each do |chore| %>
  <tr>
    <td><%= chore.child.name %></td>
    <td><%= chore.task.name %></td>
    <td align="center"><%= chore.due_on.strftime("%m/%d/%Y") %></td>
    <td align="center"><%= chore.completed %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"></p>

<p>
  <b>Child:</b>
  <%= @chore.child.name %>
</p>

<p>
  <b>Task:</b>
  <%= @chore.task.name %>
</p>

<p>
  <b>Due on:</b>
  <%= @chore.due_on.strftime("%m/%d/%Y") %>
</p>

<p>
  <b>Completed:</b>
  <%= @chore.status %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChoreTracker :: <%= controller.controller_name.capitalize %></title>
  <link rel="shortcut icon" href="/gc_favicon.ico" type="image/x-icon" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <div id="header">
      <%= link_to(image_tag('qu_vu.jpg'), chores_path) %>
    </div>
    <br />
     <div id="nav">
      <ul>
        <!-- OPTIONS FOR EVERYONE -->
        <li><%= link_to 'Children', children_path %></li>
        <li><%= link_to 'Chores', chores_path %></li>
        <li><%= link_to 'Tasks', tasks_path %></li>
      </ul>
    </div> <!-- end of nav div -->
    <div style="clear:both;"></div>
      <div id="body">
      <p style="color: green" id="notice"><%= flash[:notice] %></p>
      <%= yield %>
    </div> <!-- end of body div -->

  </div><!-- end of wrap div -->
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h2>Tasks in the system</h2>

<table>
  <tr>
    <th width="120" align="left">Name</th>
    <th width="120" >Points</th>
    <th width="120">Active</th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td align="center"><%= task.points %></td>
    <td align="center"><%= task.active ? "Yes" : "No" %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Points:</strong>
  <%= @task.points %>
</p>

<p>
  <strong>Active:</strong>
  <%= @task.active %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>